version: '3.8'

services:
  web:
    build: .
    container_name: code_cash_web
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    environment:
      # Diese Werte werden in Portainer als Environment Variables gesetzt
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
